apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # so it can only be used by one pod
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql-sc
  hostPath:
    path: /home/wms/self-train/mysql-phpmyadmin/v4-StatefulSet/storage
