apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_USER
          value: "testuser"
        - name: MYSQL_PASSWORD
          value: "test123"
        - name: MYSQL_DATABASE
          value: "testdb"
        ports:
        - containerPort: 3306
 
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvclaim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306 
  clusterIP: None
